version: '3.8'

services:
  app:
    container_name: frpc-web
    image: ghcr.io/yancj9ya/frpcweb:latest
    environment:
      - PORT=5173
    volumes:
      - ./frpc.toml:/app/frpc.toml
      - ./app_config.json:/app/app_config.json
    network_mode: "host"
    restart: always
